#import "/src/style.typ": *

With the growing prevalence of robots in our daily lives and the advancements in _cyber-physical systems_ enabling more complex on-robot control, a flurry of new learning-based techniques has emerged. Specifically, _reinforcement learning_ has seen great adoption across the robotics community and industry. However, practitioners often struggle when applying such learning-based techniques to real robots as they face: (1) Difficulties in guiding learning towards finding controllers that fulfill their intended objectives, (2) Robots that behave erratically upon deployment, even when performing well in simulation, (3) Catastrophic forgetting when adapting controllers to real-world data, and (4) Long training runs due to the low sample efficiency of popular RL algorithms. We classify these issues as instances of the "intent-to-reality gap"—the discrepancy between designer intention and deployed robot behavior.

Examining what contributes to this gap, we identify critical expressiveness limitations in how objectives are specified and optimized. Large discrepancies exist between user intention represented as scalar reward functions and the behavior produced by policy optimization. Even in simulated benchmark tasks designed by researchers in the field, these reward functions tend to be difficult to interpret and contain redundant terms. They often produce algorithm, environment, and even seed-specific reward formulations.

If rewards are the answer, then what is the question? The _reward hypothesis_ states that scalar rewards can precisely represent all that we care about in robot control. However, it says nothing of the difficulty in expressing such rewards. Can adding more structure to this interface of value functions and rewards help us express our intentions more precisely?

To address this question, we take a fulfillment-centric approach, treating objectives as continuous and bounded logical values to fulfill. Fulfillment functions serve as semantic bridges, translating intuitive judgments like "this robot moves 80% as smooth as I want, and 30% as fast as I want" into mathematically precise differentiable and composable values that remain aligned with intention throughout optimization. Using generalized means as continuous logic aggregators, fulfillments enable semantic-preserving composition of complex relationships with gradient-based optimization. 

This approach, combined with careful embedded system design, enabled us to achieve state-of-the-art results: the first RL system outperforming classical PID controllers in quadrotor deployment achieving 50-80% power reductions, live and robust neural network adaptation, and consistent policy search with up to 6.4× speedup across various robotic domains. These results demonstrate that bridging the intent-to-reality gap requires precise objective specification supported by principled architectural design.

// #manual_sampler(fill: accent1_gradient, width: 100%, height: 2em, samples: 100)
// #manual_sampler(fill: accent2_gradient, width: 100%, height: 2em, samples: 100)
// #manual_sampler(fill: accent3_gradient, width: 100%, height: 2em, samples: 100)
// #manual_sampler(fill: primary_gradient, width: 100%, height: 2em, samples: 100)