#import "commands.typ": *
#import "@preview/suiji:0.4.0": *

This Ph.D., like with many others, was a journey full of challenges, both technical and personal. With an abundance of external difficulties comes an abundance of support, and without everyone who has helped me along the way, I would not have been able to complete this work. In so many ways, it's the people around me that made producing this work fulfilling.  
In no particular order (in fact I randomized it), I would like to thank:
#let rng = gen-rng-f(42)
#let (_, shuffled) = shuffle-f(rng, (
  [Sarah Mabsout],
  [Suad Taher],
  [Ahmad Hawilo],
  [Malak Mabsout],
  [Layla Mabsout],
  [Yasma Hawilo],
  [Tamer Hawilo],
  [The Large Mohammed Mabsout],
  [The Small Mohammed Mabsout],
  [Raed Mabsout],
  [Fadia Mudawar],
  [Ahmed Mudawar],
  [Yasser Karout],
  [Mazen Zahreddine],
  [Mohammad Farhat],
  [Maged Kadri],
  [Hadi Sharafeddine],
  [Karim Kabalan],
  [Jad Rawda],
  [Rodrigue Haddad],
  [Dina Bashkirova],
  [Renato Mancuso],
  [Sabrina Neuman],
  [Kate Saenko],
  [Chuchu Fan],
  [Meng Yue],
  [Koneshka Bandyopadhyay],
  [Patrick Carpanedo],
  [Yann Arif],
  [Parul Sohal],
  [Golsana Gaemi],
  [Shahin Roozkhosh],
  [Alp Yilmaz],
  [Ahmad Ahmad],
  [Mohamad Tassabehji],
  [Ibrahim Youssef],
  [Rich West],
  [Marco Gaboardi],
  [Bingzhuo Zhong],
  [Eshed Ohn-Bar],
  [Daniele Ottaviano],
  [CJ Parra],
  [Weifan Chen],
  [Ivan Izhbirdeev],
  [Sid Mysore],
  [Mattia Nicolella],
  [Francesco Ciraolo],
  [Mattias Ou],
  [Hyunjin Jung],
  [Alessandra María Lanz],
  [Jiayi Shen],
  [Nicolas AlHaddad],
  [Hassan Saade],
  [Charlie Payne],
  [Maya Zakharia],
  [Diala Nicolas],
  [Rene Adaimi],
  [Amanda Castagna],
  [Maurice AbouJaoudeh],
  [Valeria Saccà],
  [Elie Abdo],
  [Omar Itani],
  [Sara Maria Oud],
  [Ayantika Saha],
  [Hassan Ghiye],
  [Jihad Dakkak],
  [Ramzi Mabsout],
  [Kinan Dak Albab],
  [Abdelrahman Ahmed Omar Ahmed Abdelgawad],
  [Abhinav Pomalapally],
  [Assaf Kfoury],
  [Rawane Issa],
  [Sisa Poemape],
))

#shuffled.map(x => x).join([ $and$ ]) $and ...$
#v(1fr)
If I wrote down how each person mentioned and unmentioned contributed, there would not be enough space for my thesis.